### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by ceelogre** [atlp-rwanda/atlp-pulse-fn#315]
# Description

One is able to submit a form with empty fields.
<img width="1186" alt="image" src="https://github.com/atlp-rwanda/atlp-pulse-fn/assets/5022823/67cadce2-f6d8-43f9-8e81-bb5ea853b312">

**Comment by nshutip** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix input validation issue on the coordinator dashboard.](https://trello.com/c/wydeJVT5/172-fix-input-validation-issue-on-the-coordinator-dashboard)
