### ISSUE TITLE
Notifications redirect

### ISSUE THREAD

**Issue by ceelogre** [atlp-rwanda/atlp-pulse-fn#507]
# Description

The notification for an updated ratings in the admin panel redirects to `/ratings`. This route is not accessible to admins.
![Image](https://github.com/user-attachments/assets/c9222574-9445-4e27-aea6-06ae006388ac)

**Comment by elijahladdie** [comment]
This page is changed be accessible on `/updated-ratings`
![image](https://github.com/user-attachments/assets/e2f6bb9d-8fba-4ba7-8a4c-2f5f340508f8)
@Salim-54 @ceelogre
